apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 77.9.1
    namespace: monitoring
    valuesFile: values-77.9.1.yaml

namespace: monitoring