apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 77.11.0
    namespace: observability
    valuesFile: values.yaml

namespace: observability
